name: Cache segments (MEGA)

on:
  workflow_dispatch:

jobs:
  cache-segments:
    runs-on: ubuntu-22.04

    steps:
    # ----------------------------------------
    # Install tools
    # ----------------------------------------
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y unzip megatools

    # ----------------------------------------
    # Cache segments
    # ----------------------------------------
    - name: Restore Segments cache
      uses: actions/cache@v4
      with:
        path: segments
        key: segments-mega-24-${{ runner.os }}

    # ----------------------------------------
    # Download if cache miss
    # ----------------------------------------
    - name: Download segments (if needed)
      run: |
        if [ ! -d segments ]; then
          echo "📥 Cache miss → downloading segments"

          mkdir -p segments_zip

          megadl "https://mega.nz/file/c2c31YIJ#0EMTKBPT_Bca81d0yLY_C7I3qX0eq_jVbHMUQ6aBvas" \
            --path segments_zip

          mkdir -p segments
          unzip -o segments_zip/*.zip -d segments

        else
          echo "✅ segments restored from cache"
        fi
