name: Cache segments (MEGA)

on:
  workflow_dispatch:

jobs:
  cache-segments:
    runs-on: ubuntu-22.04

    steps:
    # ----------------------------------------
    # Install tools
    # ----------------------------------------
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y unzip megatools

    # ----------------------------------------
    # Cache segments
    # ----------------------------------------
    - name: Restore Segments cache
      uses: actions/cache@v4
      with:
        path: models
        key: taki_model-${{ runner.os }}

    # ----------------------------------------
    # Download if cache miss
    # ----------------------------------------
    - name: Download segments (if needed)
      run: |
        if [ ! -d segments ]; then
          echo "📥 Cache miss → downloading segments"

          mkdir -p segments_zip

          megadl "https://mega.nz/file/Aq1z2ZyA#OmKTahs0XMAnLFQ9sIvNU0sWDgtePDhSwU8lKZkqFfE" \
            --path segments_zip

          mkdir -p models
          unzip -o segments_zip/*.zip -d models

        else
          echo "✅ segments restored from cache"
        fi
