name: VTM Encode Emon→ Google Drive

on:
  workflow_dispatch:

jobs:
  encode:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        VIDEO_ID: [901,902,903,904,905,906,907,908,909,910,911,912,913,914,915,916,917,918,919,920,921,922,923,924,925,926,927,928,929,930,931,932,933,934,935,936,937,938,939,940,941,942,943,944,945,946,947,948,949,950,951,952,953,954,955,956,957,958,959,960,961,962,963,964,965,966,967,968,969,970,971,972,973,974,975,976,977,978,979,980,981,982,983,984,985,986,987,988,989,990,991,992,993,994,995,996,997,998,999,1000]

    env:
      WIDTH: 512
      HEIGHT: 512
      FPS: 24
      QP: 51
      GOP: 8
      STARTS: "1 25 49 73 97"

    steps:
      - uses: actions/checkout@v4

      - name: Restore VTM binary
        uses: actions/cache@v4
        with:
          path: VTM/bin
          key: vtm-20.2-v1-Linux

      - name: Restore YUV segments
        uses: actions/cache@v4
        with:
          path: segments
          key: segments-mega-24-Linux

      - name: Locate EncoderApp
        run: |
          ENCODER=$(find VTM/bin -type f \( -name "EncoderAppStatic*" -o -name "EncoderApp*" \) | head -n1)
          echo "ENCODER=$ENCODER" >> $GITHUB_ENV

      - name: Encode segments
        run: |
          set -e

          VIDEO_ID=${{ matrix.VIDEO_ID }}
          CFG="cfg/experimental/encoder_lowdelay_P_vtm_FixedQP_GOP_8.cfg"

          OUTDIR=encoded_segments_ac/seg_${VIDEO_ID}
          mkdir -p "$OUTDIR"

          LOG=$OUTDIR/encoding_summary_vid_${VIDEO_ID}.txt

          for START in $STARTS; do
            END=$((START+7))

            "$ENCODER" \
              -c "$CFG" \
              -i "segments/Segments_ac_24/seg_${VIDEO_ID}/${VIDEO_ID}_F_${START}_to_${END}_${WIDTH}_${HEIGHT}_${FPS}.yuv" \
              -b "$OUTDIR/B_${VIDEO_ID}_F_${START}_to_${END}_${WIDTH}_${HEIGHT}_${FPS}.bin" \
              -o "$OUTDIR/C_${VIDEO_ID}_F_${START}_to_${END}_${WIDTH}_${HEIGHT}_${FPS}_GOP${GOP}_QP${QP}.yuv" \
              -wdt $WIDTH \
              -hgt $HEIGHT \
              -fr $FPS \
              -f 7 \
              -q $QP >>"$LOG" 2>&1
          done

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONFIG_BASE64 }}" | base64 -d > ~/.config/rclone/rclone.conf

      - name: Upload to Google Drive
        run: |
          rclone copy encoded_segments_ac dataset:Segments_24/encoded_segments_24_${QP} --progress
