name: VTM Encode Segments 351-700 → Google Drive

on:
  workflow_dispatch:

jobs:
  encode:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        VIDEO_ID: [501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700]

    env:
      WIDTH: 512
      HEIGHT: 512
      FPS: 50
      QP: 51
      GOP: 8
      STARTS: "1 51 101 151 201"

    steps:
      - uses: actions/checkout@v4

      - name: Restore VTM binary
        uses: actions/cache@v4
        with:
          path: VTM/bin
          key: vtm-20.2-v1-Linux

      - name: Restore YUV segments
        uses: actions/cache@v4
        with:
          path: segments
          key: segments-mega-50-Linux

      - name: Locate EncoderApp
        run: |
          ENCODER=$(find VTM/bin -type f \( -name "EncoderAppStatic*" -o -name "EncoderApp*" \) | head -n1)
          echo "ENCODER=$ENCODER" >> $GITHUB_ENV

      - name: Encode segments
        run: |
          set -e

          VIDEO_ID=${{ matrix.VIDEO_ID }}
          CFG="cfg/experimental/encoder_lowdelay_P_vtm_FixedQP_GOP_8.cfg"

          OUTDIR=encoded_segments_ac/seg_${VIDEO_ID}
          mkdir -p "$OUTDIR"

          LOG=$OUTDIR/encoding_summary_vid_${VIDEO_ID}.txt

          for START in $STARTS; do
            END=$((START+7))

            "$ENCODER" \
              -c "$CFG" \
              -i "segments/Segments_ac_50/seg_${VIDEO_ID}/${VIDEO_ID}_F_${START}_to_${END}_${WIDTH}_${HEIGHT}_${FPS}.yuv" \
              -b "$OUTDIR/B_${VIDEO_ID}_F_${START}_to_${END}_${WIDTH}_${HEIGHT}_${FPS}.bin" \
              -o "$OUTDIR/C_${VIDEO_ID}_F_${START}_to_${END}_${WIDTH}_${HEIGHT}_${FPS}_GOP${GOP}_QP${QP}.yuv" \
              -wdt $WIDTH \
              -hgt $HEIGHT \
              -fr $FPS \
              -f 7 \
              -q $QP >>"$LOG" 2>&1
          done

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONFIG_BASE64 }}" | base64 -d > ~/.config/rclone/rclone.conf

      - name: Upload to Google Drive
        run: |
          rclone copy encoded_segments_ac dataset:Segments/encoded_segments_50_51 --progress
