name: VTM Encode Segments 351-700 → Google Drive

on:
  workflow_dispatch:

jobs:
  encode:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        VIDEO_ID: [201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350]

    env:
      WIDTH: 512
      HEIGHT: 512
      FPS: 60
      QP: 37
      GOP: 8
      STARTS: "1 61 121 181 241"

    steps:
      - uses: actions/checkout@v4

      - name: Restore VTM binary
        uses: actions/cache@v4
        with:
          path: VTM/bin
          key: vtm-20.2-v1-Linux

      - name: Restore YUV segments
        uses: actions/cache@v4
        with:
          path: segments
          key: segments-mega-60-Linux

      - name: Locate EncoderApp
        run: |
          ENCODER=$(find VTM/bin -type f \( -name "EncoderAppStatic*" -o -name "EncoderApp*" \) | head -n1)
          echo "ENCODER=$ENCODER" >> $GITHUB_ENV

      - name: Encode segments
        run: |
          set -e

          VIDEO_ID=${{ matrix.VIDEO_ID }}
          CFG="cfg/experimental/encoder_lowdelay_P_vtm_FixedQP_GOP_8.cfg"

          OUTDIR=encoded_segments_ac/seg_${VIDEO_ID}
          mkdir -p "$OUTDIR"

          LOG=$OUTDIR/encoding_summary_vid_${VIDEO_ID}.txt

          for START in $STARTS; do
            END=$((START+7))

            "$ENCODER" \
              -c "$CFG" \
              -i "segments/Segments_ac_60/seg_${VIDEO_ID}/${VIDEO_ID}_F_${START}_to_${END}_${WIDTH}_${HEIGHT}_${FPS}.yuv" \
              -b "$OUTDIR/B_${VIDEO_ID}_F_${START}_to_${END}_${WIDTH}_${HEIGHT}_${FPS}.bin" \
              -o "$OUTDIR/C_${VIDEO_ID}_F_${START}_to_${END}_${WIDTH}_${HEIGHT}_${FPS}_GOP${GOP}_QP${QP}.yuv" \
              -wdt $WIDTH \
              -hgt $HEIGHT \
              -fr $FPS \
              -f 7 \
              -q $QP >>"$LOG" 2>&1
          done

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONFIG_BASE64 }}" | base64 -d > ~/.config/rclone/rclone.conf

      - name: Upload to Google Drive
        run: |
          rclone copy encoded_segments_ac dataset:Segments_60/encoded_segments_60_37 --progress
