name: VTM Encode Taki → Google Drive

on:
  workflow_dispatch:

jobs:
  encode:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        VIDEO_ID: [801,802,803,804,805,806,807,808,809,810,811,812,813,814,815,816,817,818,819,820,821,822,823,824,825,826,827,828,829,830,831,832,833,834,835,836,837,838,839,840,841,842,843,844,845,846,847,848,849,850,851,852,853,854,855,856,857,858,859,860,861,862,863,864,865,866,867,868,869,870,871,872,873,874,875,876,877,878,879,880,881,882,883,884,885,886,887,888,889,890,891,892,893,894,895,896,897,898,899,900]

    env:
      WIDTH: 512
      HEIGHT: 512
      FPS: 30
      QP: 51
      GOP: 8
      STARTS: "1 31 61 91 121"

    steps:
      - uses: actions/checkout@v4

      - name: Restore VTM binary
        uses: actions/cache@v4
        with:
          path: VTM/bin
          key: vtm-20.2-v1-Linux

      - name: Restore YUV segments
        uses: actions/cache@v4
        with:
          path: segments
          key: segments-mega-30-Linux

      - name: Locate EncoderApp
        run: |
          ENCODER=$(find VTM/bin -type f \( -name "EncoderAppStatic*" -o -name "EncoderApp*" \) | head -n1)
          echo "ENCODER=$ENCODER" >> $GITHUB_ENV

      - name: Encode segments
        run: |
          set -e

          VIDEO_ID=${{ matrix.VIDEO_ID }}
          CFG="cfg/experimental/encoder_lowdelay_P_vtm_FixedQP_GOP_8.cfg"

          OUTDIR=encoded_segments_ac/seg_${VIDEO_ID}
          mkdir -p "$OUTDIR"

          LOG=$OUTDIR/encoding_summary_vid_${VIDEO_ID}.txt

          for START in $STARTS; do
            END=$((START+7))

            "$ENCODER" \
              -c "$CFG" \
              -i "segments/Segments_ac_30/seg_${VIDEO_ID}/${VIDEO_ID}_F_${START}_to_${END}_${WIDTH}_${HEIGHT}_${FPS}.yuv" \
              -b "$OUTDIR/B_${VIDEO_ID}_F_${START}_to_${END}_${WIDTH}_${HEIGHT}_${FPS}.bin" \
              -o "$OUTDIR/C_${VIDEO_ID}_F_${START}_to_${END}_${WIDTH}_${HEIGHT}_${FPS}_GOP${GOP}_QP${QP}.yuv" \
              -wdt $WIDTH \
              -hgt $HEIGHT \
              -fr $FPS \
              -f 7 \
              -q $QP >>"$LOG" 2>&1
          done

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONFIG_BASE64 }}" | base64 -d > ~/.config/rclone/rclone.conf

      - name: Upload to Google Drive
        run: |
          rclone copy encoded_segments_ac dataset:Segments_30/encoded_segments_30_${QP} --progress
