name: VTM Encode Taki → Google Drive

on:
  workflow_dispatch:

jobs:
  encode:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        VIDEO_ID: [701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,739,740,741,742,743,744,745,746,747,748,749,750,751,752,753,754,755,756,757,758,759,760,761,762,763,764,765,766,767,768,769,770,771,772,773,774,775,776,777,778,779,780,781,782,783,784,785,786,787,788,789,790,791,792,793,794,795,796,797,798,799,800]

    env:
      WIDTH: 512
      HEIGHT: 512
      FPS: 30
      QP: 37
      GOP: 8
      STARTS: "1 31 61 91 121"

    steps:
      - uses: actions/checkout@v4

      - name: Restore VTM binary
        uses: actions/cache@v4
        with:
          path: VTM/bin
          key: vtm-20.2-v1-Linux

      - name: Restore YUV segments
        uses: actions/cache@v4
        with:
          path: segments
          key: segments-mega-30-Linux

      - name: Locate EncoderApp
        run: |
          ENCODER=$(find VTM/bin -type f \( -name "EncoderAppStatic*" -o -name "EncoderApp*" \) | head -n1)
          echo "ENCODER=$ENCODER" >> $GITHUB_ENV

      - name: Encode segments
        run: |
          set -e

          VIDEO_ID=${{ matrix.VIDEO_ID }}
          CFG="cfg/experimental/encoder_lowdelay_P_vtm_FixedQP_GOP_8.cfg"

          OUTDIR=encoded_segments_ac/seg_${VIDEO_ID}
          mkdir -p "$OUTDIR"

          LOG=$OUTDIR/encoding_summary_vid_${VIDEO_ID}.txt

          for START in $STARTS; do
            END=$((START+7))

            "$ENCODER" \
              -c "$CFG" \
              -i "segments/Segments_ac_30/seg_${VIDEO_ID}/${VIDEO_ID}_F_${START}_to_${END}_${WIDTH}_${HEIGHT}_${FPS}.yuv" \
              -b "$OUTDIR/B_${VIDEO_ID}_F_${START}_to_${END}_${WIDTH}_${HEIGHT}_${FPS}.bin" \
              -o "$OUTDIR/C_${VIDEO_ID}_F_${START}_to_${END}_${WIDTH}_${HEIGHT}_${FPS}_GOP${GOP}_QP${QP}.yuv" \
              -wdt $WIDTH \
              -hgt $HEIGHT \
              -fr $FPS \
              -f 7 \
              -q $QP >>"$LOG" 2>&1
          done

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONFIG_BASE64 }}" | base64 -d > ~/.config/rclone/rclone.conf

      - name: Upload to Google Drive
        run: |
          rclone copy encoded_segments_ac dataset:Segments_30/encoded_segments_30_${QP} --progress
